services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - template_network

  postgres:
    image: postgres
    env_file:
      - '.env'
    ports:
      # Port mapping for connecting from your host (e.g., with a DB client)
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds/users.sql:/docker-entrypoint-initdb.d/02-users.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - template_network

volumes:
  postgres_data:

networks:
  template_network:
    driver: bridge